##### Where is the data? #####

basecalled_path: path/to/basecalled #where rampart will find the reads
annotated_path: path/to/csv #where rampart will find the csv reports
output_path: path/to/binned #where rampart will put the binned/ filtered files 

##### Length filters #####

min_read_length: 1
max_read_length: 1000000

##### Barcodes to process #####

# sample_name: 
barcodes: BCXX,BCYY

##### Binning options #####

# bin_by: 